development:
  adapter: postgresql
  encoding: utf8
  database: dbc_overflow_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: utf8
  database: dbc_overflow_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: dbc_overflow_production
  pool: 5
  timeout: 5000