development:
  adapter: postgresql
  encoding: unicode
  database: rails_with_rspec_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: rails_with_rspec_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: rails_with_rspec_production
  pool: 5
